--------------------------------------------------------------------------------
-- The FCode PROM of the SS20's audio in SBus slot 3 (the CS4231 + APC of
-- ts_cs4231a), read by a Sun OBP probing the slot, and the image at slot e
-- +0x1000 that names the Sun OBP's DBRI node (the core has no DBRI).
-- Generated by tools/fcode_cs4231.py; do not edit. GPL-2.0-or-later.
--------------------------------------------------------------------------------
LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;

LIBRARY work;
USE work.base_pack.ALL;

PACKAGE ts_fcode_cs4231_pack IS
  -- 32-bit big-endian words: byte n of the image is in word n/4, lane n mod 4
  -- 96 bytes, then 0xFF
  TYPE arr_fcode_cs4231 IS ARRAY(0 TO 24) OF uv32;
  CONSTANT FCODE_CS4231 : arr_fcode_cs4231 := (
    x"F1080D7C", x"00000060", x"120B5355", x"4E572C43", x"53343233", x"31020112",
    x"06736572", x"69616C01", x"1A010210", x"0C000000", x"1E010310", x"00000040",
    x"01161000", x"00000501", x"11120A69", x"6E746572", x"72757074", x"73011010",
    x"00000039", x"01111000", x"00000001", x"11011212", x"04696E74", x"72011000",
    x"FFFFFFFF");
  -- 24 bytes, then 0xFF
  TYPE arr_fcode_slote IS ARRAY(0 TO 6) OF uv32;
  CONSTANT FCODE_SLOTE : arr_fcode_slote := (
    x"F108046B", x"00000018", x"120B6462", x"72692D61", x"6273656E", x"74020100",
    x"FFFFFFFF");
END PACKAGE ts_fcode_cs4231_pack;
