#!/usr/bin/env python3
"""fcode_cs4231.py [--bin FILE [--slote]] > rtl/sun4m/ts_fcode_cs4231_pack.vhd

The SS20's two FCode images of our own (FCODE_CS4231, FCODE_SLOTE).

FCODE_CS4231, the FCode PROM of the SS20's audio "card": the SS5's CS4231 +
APC (the core's ts_cs4231a) put in SBus slot 3 (PLAN.md S1). A Sun OBP
probing the slot reads this image at the slot's base and builds the node a
Sun OBP 2.15 builds for the SS5's on-board CS4231
(docs/rom-disassembly/ss5-obp/device-tree.md):

    name         SUNW,CS4231
    device_type  serial
    reg          <slot 0x0c000000 0x40>
    interrupts   5            (SBus level 5)
    intr         <0x39 0>     (processor level 9)

The TACUS OpenBIOS does not run slot FCode; it builds the same node itself
(bios/openbios/drivers/sbus.c, sbus_probe_slot_ss10). The image is tokenized
here, from the words below, so it is our own (GPL-2.0-or-later).

FCODE_SLOTE, at SBus slot e +0x1000: a real SS20 has its DBRI there. The Sun
OBP probes slot e with a stub of its own (docs/rom-disassembly/ss20-obp-2.25,
fcode-000299a0) that byte-loads the DBRI's FCode from +0x1000, then adds the
SpeakerBox properties; the core has no DBRI, and with nothing there (0 =
end0) the node had no name, which NeXTSTEP's sbus_config faults on (a NULL
"name"). This image only names it, "dbri-absent": no OS binds a driver to it
(theirs match SUNW,DBRIe).

FCode (IEEE 1275-1994): start1 (0xf1), format, a 16-bit checksum of the bytes
after the 8-byte header, the 32-bit length (header included), the tokens,
end0. One-byte tokens 0x10-0xff, two-byte tokens 0x01xx-0x0fxx.
"""
import sys

# The IEEE 1275 names, with the OBP 2.x names in the comments
TOK = {
    'b(lit)': 0x10, 'b(")': 0x12, '+': 0x1e,
    'my-address': 0x102, 'my-space': 0x103,
    'property': 0x110,          # attribute
    'encode-int': 0x111,        # xdrint
    'encode+': 0x112,           # xdr+
    'encode-string': 0x114,     # xdrstring
    'reg': 0x116,
    'device-type': 0x11a,
    'device-name': 0x201,       # name
    'end0': 0x00,
}

# The node: ( a Forth-like list; numbers are b(lit), "..." strings b(") )
WORDS = [
    '"SUNW,CS4231', 'device-name',
    '"serial', 'device-type',
    'my-address', 0x0c000000, '+', 'my-space', 0x40, 'reg',
    5, 'encode-int', '"interrupts', 'property',
    0x39, 'encode-int', 0, 'encode-int', 'encode+', '"intr', 'property',
    'end0',
]

WORDS_SLOTE = [
    '"dbri-absent', 'device-name',
    'end0',
]


def token(t):
    return bytes([t]) if t < 0x100 else bytes([t >> 8, t & 0xff])


def body(words):
    out = b''
    for w in words:
        if isinstance(w, int):
            out += token(TOK['b(lit)']) + w.to_bytes(4, 'big')
        elif w.startswith('"'):
            s = w[1:].encode()
            out += token(TOK['b(")']) + bytes([len(s)]) + s
        else:
            out += token(TOK[w])
    return out


def image(words):
    b = body(words)
    length = 8 + len(b)
    csum = sum(b) & 0xffff
    return bytes([0xf1, 0x08]) + csum.to_bytes(2, 'big') + length.to_bytes(4, 'big') + b


def const(name, img):
    words = len(img) // 4 + 1
    img2 = img + b'\xff' * (words * 4 - len(img))
    w = [int.from_bytes(img2[i:i + 4], 'big') for i in range(0, len(img2), 4)]
    rows = []
    for i in range(0, len(w), 6):
        rows.append('    ' + ', '.join(f'x"{v:08X}"' for v in w[i:i + 6]))
    body_ = ',\n'.join(rows)
    return f'''  -- {len(img)} bytes, then 0xFF
  TYPE arr_{name.lower()} IS ARRAY(0 TO {words - 1}) OF uv32;
  CONSTANT {name} : arr_{name.lower()} := (
{body_});'''


def vhdl():
    return f'''--------------------------------------------------------------------------------
-- The FCode PROM of the SS20's audio in SBus slot 3 (the CS4231 + APC of
-- ts_cs4231a), read by a Sun OBP probing the slot, and the image at slot e
-- +0x1000 that names the Sun OBP's DBRI node (the core has no DBRI).
-- Generated by tools/fcode_cs4231.py; do not edit. GPL-2.0-or-later.
--------------------------------------------------------------------------------
LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;

LIBRARY work;
USE work.base_pack.ALL;

PACKAGE ts_fcode_cs4231_pack IS
  -- 32-bit big-endian words: byte n of the image is in word n/4, lane n mod 4
{const('FCODE_CS4231', image(WORDS))}
{const('FCODE_SLOTE', image(WORDS_SLOTE))}
END PACKAGE ts_fcode_cs4231_pack;'''


def main():
    if len(sys.argv) in (3, 4) and sys.argv[1] == '--bin':
        img = image(WORDS_SLOTE if sys.argv[3:] == ['--slote'] else WORDS)
        open(sys.argv[2], 'wb').write(img)
        return
    if len(sys.argv) != 1:
        sys.exit(__doc__)
    print(vhdl())


if __name__ == '__main__':
    main()
